spring:
  application:
    name: cookbook-cli
logging:
  level:
    net.shamansoft: DEBUG
cookbook:
  gemini:
    api-key: "SHOULD BE GENERATED AND STORED IN A SECURE PLACE, AT LEAST AS AN ENVIRONMENT VARIABLE"
    model: "gemini-2.0-flash"
    prompt: "Convert the above recipe to YAML format, using the above YAML example as a guide. Provide only the valid YAML output. Markdown formatting is allowed within YAML string values, but do not include any markdown code blocks or any other text outside of the yaml structure. Requirements: schema_version: \"1.0.0\". Generate unique recipe_version. Use current date for date_created if not specified. Format times as \"1d 2h 30m\". Use Markdown for text formatting. Use full path for medias"
    temperature: 0.1
management:
  endpoints:
    web:
      exposure:
        include: health
