spring:
  application:
    name: cookbook-cli
logging:
  level:
    net.shamansoft: DEBUG
cookbook:
  gemini:
    api-key: "SHOULD BE GENERATED AND STORED IN A SECURE PLACE, AT LEAST AS AN ENVIRONMENT VARIABLE"
    model: "gpt-3.5-turbo"
    prompt: "Convert above recipe to yaml format, using the above yaml example as a guide. Do not include any text outside of the yaml structure."
    temperature: 0.1
